{
 "title": "BitBoxBase",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_exporter_build_info, job)"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(node_exporter_build_info{job=~\"$job\"}, instance)"
   },
   {
    "name": "port",
    "label": "Port",
    "query": "label_values(node_exporter_build_info{instance=~\"$node:(.*)\"}, instance)"
   },
   {
    "name": "lightning_alias",
    "label": "Alias",
    "query": "label_values(lightning_node_info, alias)"
   },
   {
    "name": "lightning_id",
    "label": "ID",
    "query": "label_values(lightning_node_info, id)"
   },
   {
    "name": "lightning_network",
    "label": "Network",
    "query": "label_values(lightning_node_info, network)"
   },
   {
    "name": "lightning_version",
    "label": "Version",
    "query": "label_values(lightning_node_info, version)"
   },
   {
    "name": "base_hostname",
    "label": "HOSTNAME",
    "query": "label_values(base_system_info, base_hostname)"
   },
   {
    "name": "base_build_date",
    "label": "BUILD_DATE",
    "query": "label_values(base_system_info, build_date)"
   },
   {
    "name": "base_build_time",
    "label": "BUILD_TIME",
    "query": "label_values(base_system_info, build_time)"
   },
   {
    "name": "base_build_commit",
    "label": "BUILD_COMMIT",
    "query": "label_values(base_system_info, build_commit)"
   },
   {
    "name": "base_version",
    "label": "VERSION",
    "query": "label_values(base_system_info, base_version)"
   }
  ]
 },
 "panels": [
  { "title": "System health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bitcoin",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "base_systemd_bitcoind" }
   ]
  },
  {
   "title": "Electrum",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "base_systemd_electrs" }
   ]
  },
  {
   "title": "Lightning",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "base_systemd_lightningd" }
   ]
  },
  {
   "title": "Temperature",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "base_cpu_temp{instance=~\"$node.*\"} / 1000"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node:$port\",job=~\"$job\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Memory used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node:$port\",job=~\"$job\"} / node_memory_MemTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"})) * 100"
    }
   ]
  },
  {
   "title": "Root FS storage used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (sum(node_filesystem_avail_bytes{instance=~\"$node:$port\",job=~\"$job\",mountpoint=~\"/|/media/root.*\",fstype!=\"rootfs\"} * 100) / sum(node_filesystem_size_bytes{instance=~\"$node:$port\",job=~\"$job\",mountpoint=~\"/|/media/root.*\",fstype!=\"rootfs\"}))",
     "legendFormat": "rootfs"
    },
    {}
   ]
  },
  {
   "title": "Size TMPFS in memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "( sum(node_filesystem_size_bytes{instance=~\"$node:$port\",job=~\"$job\",fstype=\"tmpfs\"}) - sum(node_filesystem_avail_bytes{instance=~\"$node:$port\",job=~\"$job\",fstype=\"tmpfs\"}) ) / 20000000 ",
     "legendFormat": "rootfs"
    }
   ]
  },
  {
   "title": "SSD storage used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (instance) (1 - (node_filesystem_avail_bytes{device=~\".*nvm.*|.*sd.*\"} / node_filesystem_size_bytes{device=~\".*nvm.*|.*sd.*\"})) *100"
    }
   ]
  },
  {
   "title": "hostname",
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "content": "<center><h2>$base_hostname</h2></center>",
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 3 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "Network",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "bitcoin_network" }
   ]
  },
  {
   "title": "System details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Base image",
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
     "content": "<center><h2>$base_version</h2></center>",
     "targets": [
      {}
     ]
    },
    {
     "title": "CPU load & cooling",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 3, "y": 6 },
     "yaxes": [
      { "format": "none", "label": "load %" }
     ],
     "targets": [
      {
       "expr": "sum by (mode) (irate(node_cpu_seconds_total{job=\"node\",mode!=\"idle\"}[5m])) / 6 * 100",
       "legendFormat": "{{mode}}"
      },
      {
       "expr": "base_fan_speed{instance=~\"$node.*\"} / 255 * 100",
       "legendFormat": "fan speed %"
      },
      {
       "expr": "base_cpu_temp{instance=~\"$node.*\"} / 1000",
       "legendFormat": "temperature °C"
      }
     ]
    },
    {
     "title": "CPU frequency by type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 6 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (node_cpu_frequency_hertz{instance=~\"$node.*\",cpu=~\"[0-3]\"}) / 4",
       "legendFormat": "4x Cortex A53"
      },
      {
       "expr": "sum by (instance) (node_cpu_frequency_hertz{instance=~\"$node.*\",cpu=~\"[4-5]\"}) / 2",
       "legendFormat": "2x Cortex A72"
      }
     ]
    },
    {
     "title": "build date",
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 8 },
     "content": "<center><h2>$base_build_date</h2></center>",
     "targets": [
      {}
     ]
    },
    {
     "title": "build time",
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 10 },
     "content": "<center><h2>$base_build_time</h2></center>",
     "targets": [
      {}
     ]
    },
    {
     "title": "build commit",
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 12 },
     "content": "<center><h2>$base_build_commit</h2></center>",
     "targets": [
      {}
     ]
    },
    {
     "title": "Diskspace used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 3, "y": 14 },
     "yaxes": [
      { "format": "bytes", "label": "IO write (-) / read (+)" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=~\"$node:$port\",job=~\"$job\",fstype!=\"tmpfs\"}-node_filesystem_avail_bytes{instance=~\"$node:$port\",job=~\"$job\",fstype!=\"tmpfs\"}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Diskspace used %",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 13, "y": 14 },
     "yaxes": [
      { "format": "percentunit", "label": "IO write (-) / read (+)" }
     ],
     "targets": [
      {
       "expr": "1 - (node_filesystem_avail_bytes{instance=~\"$node:$port\",job=~\"$job\",fstype!=\"tmpfs\"}) / node_filesystem_size_bytes{instance=~\"$node:$port\",job=~\"$job\",fstype!=\"tmpfs\"}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "RAM memory",
     "type": "graph",
     "description": "Basic memory usage",
     "gridPos": { "h": 8, "w": 10, "x": 3, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "RAM Total"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_MemFree_bytes{instance=~\"$node:$port\",job=~\"$job\"} - (node_memory_Cached_bytes{instance=~\"$node:$port\",job=~\"$job\"} + node_memory_Buffers_bytes{instance=~\"$node:$port\",job=~\"$job\"})",
       "legendFormat": "RAM Used"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=~\"$node:$port\",job=~\"$job\"} + node_memory_Buffers_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "RAM Cache + Buffer"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "RAM Free"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_SwapFree_bytes{instance=~\"$node:$port\",job=~\"$job\"})",
       "legendFormat": "SWAP Used"
      }
     ]
    },
    {
     "title": "Size RAM-based TMPFS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 13, "y": 22 },
     "yaxes": [
      { "format": "bytes", "label": "IO write (-) / read (+)" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=~\"$node:$port\",job=~\"$job\",fstype=\"tmpfs\"} - node_filesystem_avail_bytes{instance=~\"$node:$port\",job=~\"$job\",fstype=\"tmpfs\"}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "RAM Memory Active / Inactive",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 3, "y": 30 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Inactive_file_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Inactive_file - File-backed memory"
      },
      {
       "expr": "node_memory_Inactive_anon_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Inactive_anon - Anonymous and swap cache"
      },
      {
       "expr": "node_memory_Active_file_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Active_file - File-backed memory"
      },
      {
       "expr": "node_memory_Active_anon_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Active_anon - Anonymous and swap cache"
      }
     ]
    },
    {
     "title": "Disk IOps",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 30 },
     "yaxes": [
      { "format": "iops", "label": "IO write (-) / read (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{instance=~\"$node:$port\",job=~\"$job\",device=~\"mmcblk1|nvme.*|sda.*\"}[5m])",
       "legendFormat": "{{device}} - Reads completed"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{instance=~\"$node:$port\",job=~\"$job\",device=~\"mmcblk1|nvme.*|sda.*\"}[5m])  ",
       "legendFormat": "{{device}} - Writes completed"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 3, "y": 38 },
     "yaxes": [
      { "format": "bytes", "label": "send (-) / receive (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{instance=~\"$node:$port\",job=~\"$job\",device!=\"lo\"}[5m])",
       "legendFormat": "recv {{device}}"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{instance=~\"$node:$port\",job=~\"$job\",device!=\"lo\"}[5m])",
       "legendFormat": "send {{device}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Services uptime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bitcoin Core uptime",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 7 },
     "targets": [
      { "expr": "base_systemd_bitcoind", "legendFormat": "up" },
      { "expr": "1 -   base_systemd_bitcoind", "legendFormat": "down" }
     ]
    },
    {
     "title": "NGINX uptime",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 7 },
     "targets": [
      { "expr": "base_systemd_nginx", "legendFormat": "up" },
      { "expr": "1 -   base_systemd_nginx", "legendFormat": "down" }
     ]
    },
    {
     "title": "Electrs uptime",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 10 },
     "targets": [
      { "expr": "base_systemd_electrs", "legendFormat": "up" },
      { "expr": "1 -   base_systemd_electrs", "legendFormat": "down" }
     ]
    },
    {
     "title": "Prometheus uptime",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 10 },
     "targets": [
      { "expr": "base_systemd_prometheus", "legendFormat": "up" },
      { "expr": "1 -   base_systemd_prometheus", "legendFormat": "down" }
     ]
    },
    {
     "title": "c-lightning uptime",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 13 },
     "targets": [
      { "expr": "base_systemd_lightningd", "legendFormat": "up" },
      { "expr": "1 -   base_systemd_lightningd", "legendFormat": "down" }
     ]
    },
    {
     "title": "Grafana uptime",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 13 },
     "targets": [
      { "expr": "base_systemd_grafana", "legendFormat": "up" },
      { "expr": "1 -   base_systemd_grafana", "legendFormat": "down" }
     ]
    },
    {
     "title": "Redis uptime",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 16 },
     "targets": [
      { "expr": "base_systemd_redis", "legendFormat": "up" },
      { "expr": "1 -   base_systemd_redis", "legendFormat": "down" }
     ]
    },
    {
     "title": "Supervisor uptime",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 16 },
     "targets": [
      { "expr": "base_systemd_bbbsupervisor", "legendFormat": "up" },
      {
       "expr": "1 -   base_systemd_bbbsupervisor",
       "legendFormat": "down"
      }
     ]
    },
    {
     "title": "Middleware uptime",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 19 },
     "targets": [
      { "expr": "base_systemd_bbbmiddleware", "legendFormat": "up" },
      { "expr": "1 - base_systemd_bbbmiddleware", "legendFormat": "down" }
     ]
    },
    {
     "title": "Fancontrol uptime",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 19 },
     "targets": [
      { "expr": "base_systemd_bbbfancontrol", "legendFormat": "up" },
      {
       "expr": "1 -   base_systemd_bbbfancontrol",
       "legendFormat": "down"
      }
     ]
    }
   ]
  },
  { "title": "Bitcoin Core", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Synced",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 8 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "bitcoin_verification_progress{instance=~\"$node:.*\"}",
     "legendFormat": "peers"
    },
    {}
   ]
  },
  {
   "title": "Bitcoin Peers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "bitcoin_peers{instance=~\"$node:.*\"}",
     "legendFormat": "peers"
    }
   ]
  },
  {
   "title": "Bitcoin blockchain",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "bitcoin_blocks{instance=~\"$node:.*\"}",
     "legendFormat": "blockheight"
    },
    {
     "expr": "bitcoin_latest_block_size{instance=~\"$node:.*\"} / 1024",
     "legendFormat": "blocksize KiB"
    }
   ]
  },
  {
   "title": "Mempool size by fee (sat/vbyte)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "electrs_mempool_vsize", "legendFormat": "{{fee_rate}}" }
   ]
  },
  {
   "title": "Chaintips",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "bitcoin_num_chaintips{instance=~\"$node:.*\"}",
     "legendFormat": "peers"
    }
   ]
  },
  {
   "title": "Tx in Mempool",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "bitcoin_mempool_size{instance=~\"$node:.*\"}",
     "legendFormat": "peers"
    }
   ]
  },
  {
   "title": "Bitcoin details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short", "label": "GB" }
     ],
     "targets": [
      {
       "expr": "bitcoin_total_bytes_recv / 1000000000",
       "legendFormat": "received"
      },
      {
       "expr": "bitcoin_total_bytes_sent  / 1000000000",
       "legendFormat": "sent"
      }
     ]
    },
    {
     "title": "electrs: blockchain sync",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 4, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "electrs_parse_blocks{type=\"indexed\"}",
       "legendFormat": "indexed blocks"
      },
      {
       "expr": "electrs_parse_blocks{type=\"duplicate\"}",
       "legendFormat": "parsed blocks"
      },
      { "expr": "electrs_index_height", "legendFormat": "index height" }
     ]
    },
    {
     "title": "Bitcoin IBD",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 14, "y": 15 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "bitcoin_ibd{instance=~\"$node:.*\"}",
       "legendFormat": "ibd"
      },
      {}
     ]
    },
    {
     "title": "Panel Title",
     "type": "text",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 15 },
     "content": "# Fees: Todo\n\n* estimatesmartfee from Bitcoin Core\n* mempool tx\n* getpeerinfo: inbound / outbound"
    }
   ]
  },
  { "title": "Lightning", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Synced",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 16 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "lightning_node_blockheight / ignoring (instance, job) bitcoin_blocks"
    },
    {}
   ]
  },
  {
   "title": "Alias",
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 16 },
   "content": "<center><h2>$lightning_alias</h2></center>",
   "targets": [
    { "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "ID",
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 10, "y": 16 },
   "content": "<center>$lightning_id</center>",
   "targets": [
    { "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Network",
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 16 },
   "content": "<center><h3>$lightning_network</h3></center>",
   "targets": [
    { "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Version",
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 16 },
   "content": "<center><h3>$lightning_version</h3></center>",
   "targets": [
    { "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Peers connected",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(lightning_peer_connected)" },
    {}
   ]
  },
  {
   "title": "Channels active",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(lightning_peer_channels)" },
    {}
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(lightning_peer_connected)",
     "legendFormat": "Total"
    },
    { "expr": "sum(lightning_peer_connected)", "legendFormat": "connected" }
   ]
  },
  {
   "title": "Lightning funds",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "sats" }
   ],
   "targets": [
    { "expr": "lightning_funds_output", "legendFormat": "on chain" },
    { "expr": "lightning_funds_channel", "legendFormat": "in channels" }
   ]
  },
  {
   "title": "Peers inactive",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 21 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(lightning_peer_connected) - sum(lightning_peer_connected)) / count(lightning_peer_connected)"
    },
    {}
   ]
  },
  {
   "title": "Channels inactive",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 21 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(lightning_peer_channels) - sum(lightning_peer_channels)) / count(lightning_peer_channels)"
    },
    {}
   ]
  },
  {
   "title": "Funds on-chain",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 24 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum(lightning_funds_output)" },
    {}
   ]
  },
  {
   "title": "Funds LN total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 24 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum(lightning_funds_channel)" },
    {}
   ]
  },
  {
   "title": "Channels",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count(lightning_peer_channels)", "legendFormat": "total" },
    { "expr": "sum(lightning_peer_channels)", "legendFormat": "active" },
    { "expr": "sum(lightning_channel_htlcs)", "legendFormat": "# HTLCs" }
   ]
  },
  {
   "title": "Channel balances",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "sats" }
   ],
   "targets": [
    {
     "expr": "sum(lightning_channel_capacity)",
     "legendFormat": "capacity"
    },
    { "expr": "sum(lightning_channel_balance)", "legendFormat": "balance" },
    {
     "expr": "sum(lightning_channel_spendable)",
     "legendFormat": "spendable"
    }
   ]
  },
  {
   "title": "LN spendable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 27 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(lightning_channel_spendable)"
    },
    {}
   ]
  },
  {
   "title": "LN receivable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 27 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(lightning_channel_balance) - sum(lightning_channel_spendable)"
    },
    {}
   ]
  },
  {
   "title": "Lightning details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    { "title": "Panel Title", "type": "text", "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 }, "content": "# Todo" }
   ]
  }
 ]
}