// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages/bbb.proto

package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BaseMiddlewareInfoOut struct {
	Blocks               int64    `protobuf:"varint,1,opt,name=Blocks,json=blocks,proto3" json:"Blocks,omitempty"`
	Difficulty           float32  `protobuf:"fixed32,2,opt,name=Difficulty,json=difficulty,proto3" json:"Difficulty,omitempty"`
	LightningAlias       string   `protobuf:"bytes,3,opt,name=LightningAlias,json=lightningAlias,proto3" json:"LightningAlias,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseMiddlewareInfoOut) Reset()         { *m = BaseMiddlewareInfoOut{} }
func (m *BaseMiddlewareInfoOut) String() string { return proto.CompactTextString(m) }
func (*BaseMiddlewareInfoOut) ProtoMessage()    {}
func (*BaseMiddlewareInfoOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbb_6f68adb0d3b3d211, []int{0}
}
func (m *BaseMiddlewareInfoOut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseMiddlewareInfoOut.Unmarshal(m, b)
}
func (m *BaseMiddlewareInfoOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseMiddlewareInfoOut.Marshal(b, m, deterministic)
}
func (dst *BaseMiddlewareInfoOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseMiddlewareInfoOut.Merge(dst, src)
}
func (m *BaseMiddlewareInfoOut) XXX_Size() int {
	return xxx_messageInfo_BaseMiddlewareInfoOut.Size(m)
}
func (m *BaseMiddlewareInfoOut) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseMiddlewareInfoOut.DiscardUnknown(m)
}

var xxx_messageInfo_BaseMiddlewareInfoOut proto.InternalMessageInfo

func (m *BaseMiddlewareInfoOut) GetBlocks() int64 {
	if m != nil {
		return m.Blocks
	}
	return 0
}

func (m *BaseMiddlewareInfoOut) GetDifficulty() float32 {
	if m != nil {
		return m.Difficulty
	}
	return 0
}

func (m *BaseMiddlewareInfoOut) GetLightningAlias() string {
	if m != nil {
		return m.LightningAlias
	}
	return ""
}

type BaseSystemEnvOut struct {
	Network              string   `protobuf:"bytes,1,opt,name=Network,json=network,proto3" json:"Network,omitempty"`
	ElectrsRPCPort       string   `protobuf:"bytes,2,opt,name=ElectrsRPCPort,json=electrsRPCPort,proto3" json:"ElectrsRPCPort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseSystemEnvOut) Reset()         { *m = BaseSystemEnvOut{} }
func (m *BaseSystemEnvOut) String() string { return proto.CompactTextString(m) }
func (*BaseSystemEnvOut) ProtoMessage()    {}
func (*BaseSystemEnvOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbb_6f68adb0d3b3d211, []int{1}
}
func (m *BaseSystemEnvOut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseSystemEnvOut.Unmarshal(m, b)
}
func (m *BaseSystemEnvOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseSystemEnvOut.Marshal(b, m, deterministic)
}
func (dst *BaseSystemEnvOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseSystemEnvOut.Merge(dst, src)
}
func (m *BaseSystemEnvOut) XXX_Size() int {
	return xxx_messageInfo_BaseSystemEnvOut.Size(m)
}
func (m *BaseSystemEnvOut) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseSystemEnvOut.DiscardUnknown(m)
}

var xxx_messageInfo_BaseSystemEnvOut proto.InternalMessageInfo

func (m *BaseSystemEnvOut) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *BaseSystemEnvOut) GetElectrsRPCPort() string {
	if m != nil {
		return m.ElectrsRPCPort
	}
	return ""
}

type BaseResyncOut struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseResyncOut) Reset()         { *m = BaseResyncOut{} }
func (m *BaseResyncOut) String() string { return proto.CompactTextString(m) }
func (*BaseResyncOut) ProtoMessage()    {}
func (*BaseResyncOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbb_6f68adb0d3b3d211, []int{2}
}
func (m *BaseResyncOut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseResyncOut.Unmarshal(m, b)
}
func (m *BaseResyncOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseResyncOut.Marshal(b, m, deterministic)
}
func (dst *BaseResyncOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseResyncOut.Merge(dst, src)
}
func (m *BaseResyncOut) XXX_Size() int {
	return xxx_messageInfo_BaseResyncOut.Size(m)
}
func (m *BaseResyncOut) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseResyncOut.DiscardUnknown(m)
}

var xxx_messageInfo_BaseResyncOut proto.InternalMessageInfo

type BaseSystemEnvIn struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseSystemEnvIn) Reset()         { *m = BaseSystemEnvIn{} }
func (m *BaseSystemEnvIn) String() string { return proto.CompactTextString(m) }
func (*BaseSystemEnvIn) ProtoMessage()    {}
func (*BaseSystemEnvIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbb_6f68adb0d3b3d211, []int{3}
}
func (m *BaseSystemEnvIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseSystemEnvIn.Unmarshal(m, b)
}
func (m *BaseSystemEnvIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseSystemEnvIn.Marshal(b, m, deterministic)
}
func (dst *BaseSystemEnvIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseSystemEnvIn.Merge(dst, src)
}
func (m *BaseSystemEnvIn) XXX_Size() int {
	return xxx_messageInfo_BaseSystemEnvIn.Size(m)
}
func (m *BaseSystemEnvIn) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseSystemEnvIn.DiscardUnknown(m)
}

var xxx_messageInfo_BaseSystemEnvIn proto.InternalMessageInfo

type BaseResyncIn struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseResyncIn) Reset()         { *m = BaseResyncIn{} }
func (m *BaseResyncIn) String() string { return proto.CompactTextString(m) }
func (*BaseResyncIn) ProtoMessage()    {}
func (*BaseResyncIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbb_6f68adb0d3b3d211, []int{4}
}
func (m *BaseResyncIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseResyncIn.Unmarshal(m, b)
}
func (m *BaseResyncIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseResyncIn.Marshal(b, m, deterministic)
}
func (dst *BaseResyncIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseResyncIn.Merge(dst, src)
}
func (m *BaseResyncIn) XXX_Size() int {
	return xxx_messageInfo_BaseResyncIn.Size(m)
}
func (m *BaseResyncIn) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseResyncIn.DiscardUnknown(m)
}

var xxx_messageInfo_BaseResyncIn proto.InternalMessageInfo

type BitBoxBaseIn struct {
	// Types that are valid to be assigned to BitBoxBaseIn:
	//	*BitBoxBaseIn_BaseSystemEnvIn
	//	*BitBoxBaseIn_BaseResyncIn
	BitBoxBaseIn         isBitBoxBaseIn_BitBoxBaseIn `protobuf_oneof:"bitBoxBaseIn"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *BitBoxBaseIn) Reset()         { *m = BitBoxBaseIn{} }
func (m *BitBoxBaseIn) String() string { return proto.CompactTextString(m) }
func (*BitBoxBaseIn) ProtoMessage()    {}
func (*BitBoxBaseIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbb_6f68adb0d3b3d211, []int{5}
}
func (m *BitBoxBaseIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BitBoxBaseIn.Unmarshal(m, b)
}
func (m *BitBoxBaseIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BitBoxBaseIn.Marshal(b, m, deterministic)
}
func (dst *BitBoxBaseIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BitBoxBaseIn.Merge(dst, src)
}
func (m *BitBoxBaseIn) XXX_Size() int {
	return xxx_messageInfo_BitBoxBaseIn.Size(m)
}
func (m *BitBoxBaseIn) XXX_DiscardUnknown() {
	xxx_messageInfo_BitBoxBaseIn.DiscardUnknown(m)
}

var xxx_messageInfo_BitBoxBaseIn proto.InternalMessageInfo

type isBitBoxBaseIn_BitBoxBaseIn interface {
	isBitBoxBaseIn_BitBoxBaseIn()
}

type BitBoxBaseIn_BaseSystemEnvIn struct {
	BaseSystemEnvIn *BaseSystemEnvIn `protobuf:"bytes,1,opt,name=baseSystemEnvIn,proto3,oneof"`
}

type BitBoxBaseIn_BaseResyncIn struct {
	BaseResyncIn *BaseResyncIn `protobuf:"bytes,2,opt,name=baseResyncIn,proto3,oneof"`
}

func (*BitBoxBaseIn_BaseSystemEnvIn) isBitBoxBaseIn_BitBoxBaseIn() {}

func (*BitBoxBaseIn_BaseResyncIn) isBitBoxBaseIn_BitBoxBaseIn() {}

func (m *BitBoxBaseIn) GetBitBoxBaseIn() isBitBoxBaseIn_BitBoxBaseIn {
	if m != nil {
		return m.BitBoxBaseIn
	}
	return nil
}

func (m *BitBoxBaseIn) GetBaseSystemEnvIn() *BaseSystemEnvIn {
	if x, ok := m.GetBitBoxBaseIn().(*BitBoxBaseIn_BaseSystemEnvIn); ok {
		return x.BaseSystemEnvIn
	}
	return nil
}

func (m *BitBoxBaseIn) GetBaseResyncIn() *BaseResyncIn {
	if x, ok := m.GetBitBoxBaseIn().(*BitBoxBaseIn_BaseResyncIn); ok {
		return x.BaseResyncIn
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*BitBoxBaseIn) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _BitBoxBaseIn_OneofMarshaler, _BitBoxBaseIn_OneofUnmarshaler, _BitBoxBaseIn_OneofSizer, []interface{}{
		(*BitBoxBaseIn_BaseSystemEnvIn)(nil),
		(*BitBoxBaseIn_BaseResyncIn)(nil),
	}
}

func _BitBoxBaseIn_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*BitBoxBaseIn)
	// bitBoxBaseIn
	switch x := m.BitBoxBaseIn.(type) {
	case *BitBoxBaseIn_BaseSystemEnvIn:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BaseSystemEnvIn); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("BitBoxBaseIn.BitBoxBaseIn has unexpected type %T", x)
	}
	return nil
}

func _BitBoxBaseIn_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*BitBoxBaseIn)
	switch tag {
	case 1: // bitBoxBaseIn.baseSystemEnvIn
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BaseSystemEnvIn)
		err := b.DecodeMessage(msg)
		m.BitBoxBaseIn = &BitBoxBaseIn_BaseSystemEnvIn{msg}
		return true, err
	case 2: // bitBoxBaseIn.baseResyncIn
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BaseResyncIn)
		err := b.DecodeMessage(msg)
		m.BitBoxBaseIn = &BitBoxBaseIn_BaseResyncIn{msg}
		return true, err
	default:
		return false, nil
	}
}

func _BitBoxBaseIn_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*BitBoxBaseIn)
	// bitBoxBaseIn
	switch x := m.BitBoxBaseIn.(type) {
	case *BitBoxBaseIn_BaseSystemEnvIn:
		s := proto.Size(x.BaseSystemEnvIn)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *BitBoxBaseIn_BaseResyncIn:
		s := proto.Size(x.BaseResyncIn)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type BitBoxBaseOut struct {
	// Types that are valid to be assigned to BitBoxBaseOut:
	//	*BitBoxBaseOut_BaseMiddlewareInfoOut
	//	*BitBoxBaseOut_BaseSystemEnvOut
	BitBoxBaseOut        isBitBoxBaseOut_BitBoxBaseOut `protobuf_oneof:"bitBoxBaseOut"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *BitBoxBaseOut) Reset()         { *m = BitBoxBaseOut{} }
func (m *BitBoxBaseOut) String() string { return proto.CompactTextString(m) }
func (*BitBoxBaseOut) ProtoMessage()    {}
func (*BitBoxBaseOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbb_6f68adb0d3b3d211, []int{6}
}
func (m *BitBoxBaseOut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BitBoxBaseOut.Unmarshal(m, b)
}
func (m *BitBoxBaseOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BitBoxBaseOut.Marshal(b, m, deterministic)
}
func (dst *BitBoxBaseOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BitBoxBaseOut.Merge(dst, src)
}
func (m *BitBoxBaseOut) XXX_Size() int {
	return xxx_messageInfo_BitBoxBaseOut.Size(m)
}
func (m *BitBoxBaseOut) XXX_DiscardUnknown() {
	xxx_messageInfo_BitBoxBaseOut.DiscardUnknown(m)
}

var xxx_messageInfo_BitBoxBaseOut proto.InternalMessageInfo

type isBitBoxBaseOut_BitBoxBaseOut interface {
	isBitBoxBaseOut_BitBoxBaseOut()
}

type BitBoxBaseOut_BaseMiddlewareInfoOut struct {
	BaseMiddlewareInfoOut *BaseMiddlewareInfoOut `protobuf:"bytes,1,opt,name=baseMiddlewareInfoOut,proto3,oneof"`
}

type BitBoxBaseOut_BaseSystemEnvOut struct {
	BaseSystemEnvOut *BaseSystemEnvOut `protobuf:"bytes,2,opt,name=baseSystemEnvOut,proto3,oneof"`
}

type BitBoxBaseOut_BaseResyncOut struct {
	BaseResyncOut *BaseResyncOut `protobuf:"bytes,3,opt,name=baseResyncOut,proto3,oneof"`
}

func (*BitBoxBaseOut_BaseMiddlewareInfoOut) isBitBoxBaseOut_BitBoxBaseOut() {}

func (*BitBoxBaseOut_BaseSystemEnvOut) isBitBoxBaseOut_BitBoxBaseOut() {}

func (*BitBoxBaseOut_BaseResyncOut) isBitBoxBaseOut_BitBoxBaseOut() {}

func (m *BitBoxBaseOut) GetBitBoxBaseOut() isBitBoxBaseOut_BitBoxBaseOut {
	if m != nil {
		return m.BitBoxBaseOut
	}
	return nil
}

func (m *BitBoxBaseOut) GetBaseMiddlewareInfoOut() *BaseMiddlewareInfoOut {
	if x, ok := m.GetBitBoxBaseOut().(*BitBoxBaseOut_BaseMiddlewareInfoOut); ok {
		return x.BaseMiddlewareInfoOut
	}
	return nil
}

func (m *BitBoxBaseOut) GetBaseSystemEnvOut() *BaseSystemEnvOut {
	if x, ok := m.GetBitBoxBaseOut().(*BitBoxBaseOut_BaseSystemEnvOut); ok {
		return x.BaseSystemEnvOut
	}
	return nil
}

func (m *BitBoxBaseOut) GetBaseResyncOut() *BaseResyncOut {
	if x, ok := m.GetBitBoxBaseOut().(*BitBoxBaseOut_BaseResyncOut); ok {
		return x.BaseResyncOut
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*BitBoxBaseOut) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _BitBoxBaseOut_OneofMarshaler, _BitBoxBaseOut_OneofUnmarshaler, _BitBoxBaseOut_OneofSizer, []interface{}{
		(*BitBoxBaseOut_BaseMiddlewareInfoOut)(nil),
		(*BitBoxBaseOut_BaseSystemEnvOut)(nil),
		(*BitBoxBaseOut_BaseResyncOut)(nil),
	}
}

func _BitBoxBaseOut_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*BitBoxBaseOut)
	// bitBoxBaseOut
	switch x := m.BitBoxBaseOut.(type) {
	case *BitBoxBaseOut_BaseMiddlewareInfoOut:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BaseMiddlewareInfoOut); err != nil {
			return err
		}
	case *BitBoxBaseOut_BaseSystemEnvOut:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BaseSystemEnvOut); err != nil {
			return err
		}
	case *BitBoxBaseOut_BaseResyncOut:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BaseResyncOut); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("BitBoxBaseOut.BitBoxBaseOut has unexpected type %T", x)
	}
	return nil
}

func _BitBoxBaseOut_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*BitBoxBaseOut)
	switch tag {
	case 1: // bitBoxBaseOut.baseMiddlewareInfoOut
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BaseMiddlewareInfoOut)
		err := b.DecodeMessage(msg)
		m.BitBoxBaseOut = &BitBoxBaseOut_BaseMiddlewareInfoOut{msg}
		return true, err
	case 2: // bitBoxBaseOut.baseSystemEnvOut
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BaseSystemEnvOut)
		err := b.DecodeMessage(msg)
		m.BitBoxBaseOut = &BitBoxBaseOut_BaseSystemEnvOut{msg}
		return true, err
	case 3: // bitBoxBaseOut.baseResyncOut
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BaseResyncOut)
		err := b.DecodeMessage(msg)
		m.BitBoxBaseOut = &BitBoxBaseOut_BaseResyncOut{msg}
		return true, err
	default:
		return false, nil
	}
}

func _BitBoxBaseOut_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*BitBoxBaseOut)
	// bitBoxBaseOut
	switch x := m.BitBoxBaseOut.(type) {
	case *BitBoxBaseOut_BaseMiddlewareInfoOut:
		s := proto.Size(x.BaseMiddlewareInfoOut)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *BitBoxBaseOut_BaseSystemEnvOut:
		s := proto.Size(x.BaseSystemEnvOut)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *BitBoxBaseOut_BaseResyncOut:
		s := proto.Size(x.BaseResyncOut)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*BaseMiddlewareInfoOut)(nil), "BaseMiddlewareInfoOut")
	proto.RegisterType((*BaseSystemEnvOut)(nil), "BaseSystemEnvOut")
	proto.RegisterType((*BaseResyncOut)(nil), "BaseResyncOut")
	proto.RegisterType((*BaseSystemEnvIn)(nil), "BaseSystemEnvIn")
	proto.RegisterType((*BaseResyncIn)(nil), "BaseResyncIn")
	proto.RegisterType((*BitBoxBaseIn)(nil), "BitBoxBaseIn")
	proto.RegisterType((*BitBoxBaseOut)(nil), "BitBoxBaseOut")
}

func init() { proto.RegisterFile("messages/bbb.proto", fileDescriptor_bbb_6f68adb0d3b3d211) }

var fileDescriptor_bbb_6f68adb0d3b3d211 = []byte{
	// 358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xdd, 0x6a, 0xf2, 0x40,
	0x14, 0x4c, 0x14, 0x14, 0x8f, 0xf9, 0xd1, 0x05, 0x25, 0x57, 0x1f, 0x92, 0x8b, 0x0f, 0xaf, 0x52,
	0x50, 0xe8, 0x55, 0xa1, 0x34, 0xad, 0x90, 0x40, 0xab, 0xb2, 0xed, 0x0b, 0x64, 0xe3, 0x6a, 0x83,
	0x71, 0xb7, 0x64, 0xd7, 0x5a, 0x1f, 0xa3, 0x8f, 0xd9, 0xb7, 0x28, 0xd9, 0x4a, 0xcd, 0xa6, 0x5e,
	0x9e, 0x61, 0xce, 0xcc, 0xec, 0x99, 0x05, 0xb4, 0xa3, 0x42, 0x24, 0x1b, 0x2a, 0xae, 0x08, 0x21,
	0xc1, 0x5b, 0xc1, 0x25, 0xf7, 0x0f, 0x30, 0x08, 0x13, 0x41, 0x9f, 0xb2, 0xd5, 0x2a, 0xa7, 0x87,
	0xa4, 0xa0, 0x31, 0x5b, 0xf3, 0xc5, 0x5e, 0xa2, 0x21, 0xb4, 0xc2, 0x9c, 0xa7, 0x5b, 0xe1, 0x99,
	0x23, 0x73, 0xdc, 0xc4, 0x2d, 0xa2, 0x26, 0xf4, 0x0f, 0xe0, 0x21, 0x5b, 0xaf, 0xb3, 0x74, 0x9f,
	0xcb, 0xa3, 0xd7, 0x18, 0x99, 0xe3, 0x06, 0x86, 0xd5, 0x2f, 0x82, 0xfe, 0x83, 0xf3, 0x98, 0x6d,
	0x5e, 0x25, 0xcb, 0xd8, 0xe6, 0x2e, 0xcf, 0x12, 0xe1, 0x35, 0x47, 0xe6, 0xb8, 0x83, 0x9d, 0x5c,
	0x43, 0xfd, 0x17, 0xe8, 0x95, 0xc6, 0xcf, 0x47, 0x21, 0xe9, 0x6e, 0xc6, 0xde, 0x4b, 0x4f, 0x0f,
	0xda, 0x73, 0x2a, 0x0f, 0xbc, 0xd8, 0x2a, 0xd3, 0x0e, 0x6e, 0xb3, 0x9f, 0xb1, 0x54, 0x9d, 0xe5,
	0x34, 0x95, 0x85, 0xc0, 0xcb, 0xfb, 0x25, 0x2f, 0xa4, 0x72, 0xee, 0x60, 0x87, 0x6a, 0xa8, 0xef,
	0x82, 0x5d, 0xaa, 0x62, 0x2a, 0x8e, 0x2c, 0x5d, 0xec, 0xa5, 0xdf, 0x07, 0x57, 0xb3, 0x89, 0x99,
	0xef, 0x80, 0x75, 0xe6, 0xc4, 0xcc, 0xff, 0x34, 0xc1, 0x0a, 0x33, 0x19, 0xf2, 0x8f, 0x12, 0x8e,
	0x19, 0xba, 0x01, 0x97, 0xe8, 0x3b, 0x2a, 0x4e, 0x77, 0xd2, 0x0b, 0x6a, 0x5a, 0x91, 0x81, 0xeb,
	0x54, 0x34, 0x05, 0x8b, 0x54, 0xe4, 0x55, 0xd0, 0xee, 0xc4, 0x0e, 0xaa, 0x9e, 0x91, 0x81, 0x35,
	0x52, 0xe8, 0x80, 0x45, 0x2a, 0x11, 0xfc, 0x2f, 0x13, 0xec, 0x73, 0xa6, 0xf2, 0x36, 0x73, 0x18,
	0x90, 0x4b, 0x45, 0x9d, 0xa2, 0x0d, 0x83, 0x8b, 0x35, 0x46, 0x06, 0xbe, 0xbc, 0x86, 0x6e, 0xa1,
	0x47, 0x6a, 0xf7, 0x3f, 0x45, 0xed, 0x07, 0xf5, 0x62, 0x22, 0x03, 0xff, 0x21, 0xa3, 0x6b, 0xb0,
	0x49, 0xf5, 0xd4, 0xaa, 0xe7, 0xee, 0xc4, 0x09, 0xb4, 0x02, 0x22, 0x03, 0xeb, 0xb4, 0xd0, 0x05,
	0x9b, 0x54, 0x5f, 0x46, 0x5a, 0xea, 0x27, 0x4e, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xe7, 0x5e,
	0x02, 0xe8, 0x9f, 0x02, 0x00, 0x00,
}
